Repository silverstripe/silverstripe-cms, pull requests merged in 2018-10, with the labels that each got.

#2279 FIX Update field names in Behat tests for new search form namespacing
  code/Controllers/CMSMain.php
  tests/behat/features/search-for-a-page.feature
  tests/php/Controllers/CMSMainTest.php
Labels: affects/v4, change/patch

#2283 Member should not have link tracking enabled by default
  _config/linktracking.yml
Labels: affects/v4, change/patch

#2260 do not die if there is no parent in RelativeLink
  code/model/SiteTree.php
Labels: affects/v3, change/patch

#2244 FIX Sort history viewer versions in descending order
  client/dist/js/bundle.js
  client/src/state/history/readOnePageQuery.js
Labels: affects/v4, change/patch

#2289 FIX CMSMain::duplicate() now checks canCreate() but not canEdit()
  code/Controllers/CMSMain.php
Labels: affects/v4, change/patch

#2288 MINOR Upgrade Bootstrap to 4.1.2
  package.json
  yarn.lock
Labels: affects/v4, change/minor

#2290 MINOR Enable the lazy loading for DependentPages GridField
  code/Model/SiteTree.php
Labels: affects/v4, change/minor

#2302 FIX Replace usage of Convert JSON methods with json_encode and json_decode
  code/Controllers/CMSMain.php
  code/Forms/SiteTreeURLSegmentField.php
  code/Model/SiteTree.php
  tests/php/Controllers/CMSMainTest.php
Labels: affects/v4, change/minor
