Repository silverstripe/silverstripe-cms, pull requests merged in 2018-06, with the labels that each got.

#2181 BUG Ensure errorpage is built in live mode
  code/model/ErrorPage.php
  tests/model/ErrorPageTest.php
  tests/model/ErrorPageTest.yml
Labels: affects/v3, change/patch

#2197 Update class references and array syntax in VirtualPageTest
  tests/php/Model/VirtualPageTest.php
Labels: affects/v4, change/patch

#2198 Update illegal extensions
  tests/php/Model/SiteTreeTest.php
  tests/php/Search/SearchFormTest.php
Labels: affects/v4, change/patch

#2201 Target recipe-cms 5.x-dev
  .travis.yml
Labels: affects/v5, change/patch
