Repository silverstripe/silverstripe-cms, pull requests merged in 2018-05, with the labels that each got.

#2159 Pulls/4.0/ssnaviagtor casting config
  code/Controllers/ContentController.php
Labels: affects/v4, change/patch

#2161 Tests assume default config can fail
  tests/php/Controllers/ModelAsControllerTest.php
  tests/php/Model/SiteTreeTest.php
Labels: affects/v5, change/patch

#2162 Make Behat green again, again
  .travis.yml
Labels: affects/v4, change/patch

#2165 Update URLs
  README.md
Labels: affects/v5, type/docs

#2158 NEW Add revert mutation and refactor injector transformations
  _config/graphql.yml
  client/dist/js/TinyMCE_sslink-anchor.js
  client/dist/js/TinyMCE_sslink-internal.js
  client/dist/js/bundle.js
  client/src/boot/registerComponents.js
  client/src/components/PageHistoryViewer/PageHistoryViewer.js
  client/src/state/history/revertToPageVersionMutation.js
Labels: affects/v4, change/minor

#2174 FIX Make RedirectorPage::Link compatible with SiteTree::Link
  code/model/RedirectorPage.php
Labels: affects/v3, change/patch
