Repository silverstripe/silverstripe-cms, pull requests merged in 2018-04, with the labels that each got.

#2132 FIX Correct SilverStripeNavigator correctly in templates
  code/Controllers/ContentController.php
Labels: affects/v4, change/patch

#2142 NEW Add AbsoluteLink to history viewer page GraphQL query
  _config/graphql.yml
  client/dist/js/bundle.js
  client/src/state/history/readOnePageQuery.js
Labels: affects/v4, change/minor

#2143 FIX Fixture the 'app' dir instead of mysite in unit tests
  tests/behat/serve-bootstrap.php
  tests/bootstrap.php
  tests/bootstrap/app.php
Labels: affects/v4, change/patch

#2145 BUG Fix rollback button from not working
  .travis.yml
  client/dist/js/bundle.js
  client/src/legacy/CMSMain.EditForm.js
Labels: affects/v4, change/patch, effort/easy, impact/high, type/bug
