Repository silverstripe/silverstripe-cms, pull requests merged in 2018-02, with the labels that each got.

#2098 Update reference to TestAssetStore
  tests/php/Model/FileLinkTrackingTest.php
  tests/php/Model/SiteTreeBrokenLinksTest.php
  tests/php/Model/SiteTreeFolderExtensionTest.php
  tests/php/Model/SiteTreeHTMLEditorFieldTest.php
Labels: affects/v4, change/patch, effort/easy, impact/high, type/enhancement

#2100 NEW Add extension point to CMSMain::Breadcrumbs
  code/Controllers/CMSMain.php
  code/Controllers/CMSPagesController.php
Labels: affects/v4, change/minor

#2103 BUG Use correct api to migrate version
  code/Model/SiteTree.php
Labels: affects/v5, change/patch, effort/easy, impact/high, type/bug
