Repository silverstripe/silverstripe-cms, pull requests merged in 2019-05, with the labels that each got.

#2416 FIX Use Bootstrap 4 alert for page type restriction message when adding a page
  code/Controllers/CMSPageAddController.php
Labels: affects/v4, change/patch, impact/low

#2427 FIX Allow all types of content to be linked in dependent pages
  code/Model/SiteTree.php
Labels: affects/v4, change/patch

#2362 MINOR Do not assume SiteTree's table will always be call SiteTree.
  code/Controllers/CMSMain.php
  code/Controllers/CMSSiteTreeFilter_ChangedPages.php
  code/Controllers/ModelAsController.php
  code/Model/SiteTree.php
  code/Reports/BrokenLinksReport.php
  code/Reports/RecentlyEditedReport.php
  code/Tasks/MigrateSiteTreeLinkingTask.php
  code/Tasks/SiteTreeMaintenanceTask.php
Labels: affects/v4, change/minor, feedback-required/core-team

#2441 FIX: Make test comparison less brittle in MigrateSiteTreeLinkingTaskTest
  tests/php/Tasks/MigrateSiteTreeLinkingTaskTest.php
Labels: affects/v4, change/patch

#2442 NEW Add updateHintsCacheKey extension point to fix invalid caching
  code/Controllers/CMSMain.php
Labels: affects/v4, change/patch

#2421 FIX Only add page font icon classes if there's no icon image defined
  code/Controllers/CMSPageAddController.php
  code/Controllers/LeftAndMainPageIconsExtension.php
Labels: affects/v4, change/patch

#2443 FIX Virtual page notice now uses Bootstrap 4 alerts
  code/Model/VirtualPage.php
Labels: affects/v4, change/patch
