Repository silverstripe/silverstripe-cms, pull requests merged in 2020-11, with the labels that each got.

#2612 MNT Fix broken pages with no content behat test
  tests/behat/features/view-reports.feature
Labels: affects/v4, effort/easy

#2604 ENH Disable option to create top-level pages based on permissions
  code/Controllers/CMSPageAddController.php
  tests/behat/features/create-a-page.feature
  tests/behat/src/FixtureContext.php
Labels: affects/v4, effort/easy, impact/low, type/UX, type/enhancement

#2562 FIX: Incorrect method call in savetreenode (fixes #2561)
  code/Controllers/CMSMain.php
Labels: affects/v4, change/patch, effort/easy, impact/low, type/bug
